### ISSUE TITLE
Load More doesn't respect Display Options

### ISSUE THREAD

**Issue by bogas04** [KhalisFoundation/SikhiToTheMax-Web#285]
## What went wrong ?

Clicking load more shows larivaared results.

## What should have happened instead ?

It should respect the pref.

## How can authors of this project cause the issue to occur on their systems ?

  1. Search for a shabad (larivaar disabled)
  2. Scroll down and click Load more
  3. Observe

## What were you trying the project on ?

  - Browser: Chrome
  - Browser Version: 64
  - Operating System: OS X

<img width="718" alt="screen shot 2018-01-31 at 1 17 33 pm" src="https://user-images.githubusercontent.com/6177621/35610952-54fbdf7e-0689-11e8-8e98-37ecce02d83b.png">

**Comment by tarunsingh5** [comment]
confirmed that this happens. 

interesting thing is that if you search in padchhed then turn on larivaar and then click 'load more' the results are in larivaar, if you then turn larivaar off and click 'load more' again the new results are still in larivaar

you can check this by searching "jh" in first letter anywhere

**Comment by ManjotS** [comment]
this was fixed in last push but changes to larivaar implementation must have broken it again

**Comment by tarunsingh5** [comment]
This is still not fixed - if you have larivaar selected and click "load more" it causes everything to become non-larivaar 

this is in dev only
