### ISSUE TITLE
in search tools, add checkboxes

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/SikhiToTheMax-Web#32]
so we can select more than one, ie english and punjabi translations

**Comment by navdeepsinghkhalsa** [comment]
Fixed in ea3163f

**Comment by navdeepsinghkhalsa** [comment]
A subset of these should be applied to search results page

**Comment by ManjotS** [comment]
This is working on shabad page but still does not appear on search page

**Comment by ManjotS** [comment]
closing because its addressed in #93 and #118
